FROM c-fortran-dev

# Here is the project layer, here we just clone the repo
# however for development we will just mount the local directory
# over the appropriate directory.
WORKDIR /App

ENTRYPOINT [ bash ]
